//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

#![allow(unused_imports)]

pub use super::event::Entity as Event;
pub use super::person::Entity as Person;
pub use super::stats::Entity as Stats;
